### ISSUE TITLE
Example failed to run

### ISSUE THREAD

**Issue by nguyenvanbien95** [thangchung/GrpcJsonTranscoder#7]
Hi  anh Thang Chung,
Cảm ơn anh đã phát triển bộ Transcoder này. 
Hiện tại, e lấy code về và chạy thử thì gặp lỗi như này:
`
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:5000/say/Bob  
Ocelot.Errors.Middleware.ExceptionHandlerMiddleware:Debug: requestId: 0HLPSQDD4RDKQ:00000001, previousRequestId: no previous request id, message: ocelot pipeline started
Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware:Debug: requestId: 0HLPSQDD4RDKQ:00000001, previousRequestId: no previous request id, message: Upstream url path is /say/Bob
Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware:Debug: requestId: 0HLPSQDD4RDKQ:00000001, previousRequestId: no previous request id, message: downstream templates are /Greet.Greeter/SayHello
Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware:Information: requestId: 0HLPSQDD4RDKQ:00000001, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /Greet.Greeter/SayHello
Ocelot.Authentication.Middleware.AuthenticationMiddleware:Information: requestId: 0HLPSQDD4RDKQ:00000001, previousRequestId: no previous request id, message: No authentication needed for /say/Bob
Ocelot.Authorisation.Middleware.AuthorisationMiddleware:Information: requestId: 0HLPSQDD4RDKQ:00000001, previousRequestId: no previous request id, message: /Greet.Greeter/SayHello route does not require user to be authorised
Ocelot.DownstreamUrlCreator.Middleware.DownstreamUrlCreatorMiddleware:Debug: requestId: 0HLPSQDD4RDKQ:00000001, previousRequestId: no previous request id, message: Downstream url is http://localhost:5003/Greet.Greeter/SayHello
Ocelot.Requester.Middleware.HttpRequesterMiddleware:Debug: requestId: 0HLPSQDD4RDKQ:00000001, previousRequestId: no previous request id, message: IHttpRequester returned an error, setting pipeline error
Ocelot.Requester.Middleware.HttpRequesterMiddleware:Warning: requestId: 0HLPSQDD4RDKQ:00000001, previousRequestId: no previous request id, message: Error making http request, exception: **System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: The server returned an invalid or unrecognized response.**
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ocelot.Requester.HttpClientHttpRequester.GetResponse(DownstreamContext context)
Ocelot.Responder.Middleware.ResponderMiddleware:Warning: requestId: 0HLPSQDD4RDKQ:00000001, previousRequestId: no previous request id, message: Error Code: UnableToCompleteRequestError Message: Error making http request, exception: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: The server returned an invalid or unrecognized response.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ocelot.Requester.HttpClientHttpRequester.GetResponse(DownstreamContext context) errors found in ResponderMiddleware. Setting error response for request path:/say/Bob, request method: GET
Ocelot.Errors.Middleware.ExceptionHandlerMiddleware:Debug: requestId: 0HLPSQDD4RDKQ:00000001, previousRequestId: no previous request id, message: ocelot pipeline finished
`
Anh có thể kiểm tra giúp e xem tại sao không. 
Cảm ơn anh

**Comment by nguyenvanbien95** [comment]
Em cấu hình gateway theo Option 1 thì ko chạy được. Check source thì dòng 31 trong file [DownStreamContextExtensions](https://github.com/thangchung/GrpcJsonTranscoder/blob/master/src/GrpcJsonTranscoder/DownStreamContextExtensions.cs)
`var methodPath = context.DownstreamReRoute.DownstreamPathTemplate.Value;
 var grpcAssemblyResolver = context.HttpContext.RequestServices.GetService<GrpcAssemblyResolver>();
 var methodDescriptor = grpcAssemblyResolver.FindMethodDescriptor(methodPath.Split('/').Last().ToUpperInvariant());
`
không lấy được grpcAssemblyResolver.

phải bổ sung theo hướng dẫn (Option 2) thì cần cấu hình thêm ở file StartUp.cs
`services.AddGrpcJsonTranscoder(() => new GrpcAssemblyResolver().ConfigGrpcAssembly(typeof(Greeter.GreeterClient).Assembly));`
thì mới chạy được.
=> Chỗ này e chưa hiểu là do e cấu hình sai hay hướng dẫn gộp chung phần cấu hình file StartUp.cs.

**Comment by thangchung** [comment]
hi Bien, thank you for your information. I will do a double check due to the new .NET Core 3.0 SDK 

```json
HTTP/1.1 GET http://localhost:5000/say/Bob Ocelot.Errors.Middleware.ExceptionHandlerMiddleware:Debug: requestId: 0HLPSQDD4RDKQ:00000001, previousRequestId: no previous request id, message: ocelot pipeline started
```

The HTTP/1.1 should not be happen here, because of HTTP/2 is a default mode for gRPC.

I am working on it at https://github.com/vietnam-devs/coolstore-microservices/tree/develop/src/gateways/webapi-gateway

**Comment by nguyenvanbien95** [comment]
Of course, HTTP/2 is default for gRPC but in this case, I was using Postman for test Api-gateway. So, it is HTTP/1.1.
I am confused when reading the guide at Readme.md. That is config between Option 1 and Option 2.
Can you rewrite for Option 1? I saw that services is imported is very important. So, it should highlight.

**Comment by thangchung** [comment]
@nguyenvanbien95 Agree with you about it. By the time, see the Ocelot gateway works with GrpcJsonTranscoder at https://github.com/vietnam-devs/coolstore-microservices/tree/develop/src/gateways/webapi-gateway, and it configures for the downstream services at https://github.com/vietnam-devs/coolstore-microservices/tree/develop/src/microservices

To get starting, run the command below

```
# at root coolstore-microservices project 
$ # docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
```

Remember to change `/c/Users/<your windows user path>/.nuget/packages`, if you run it on Windows.

I will fix the readme for this project soon as soon as I finish to test it on coolstore-microservices project. Thank you for your interesting on this project
