### ISSUE TITLE
Ocelot grpc without SSL

### ISSUE THREAD

**Issue by mihaimyh** [thangchung/GrpcJsonTranscoder#9]
Hi,

I am trying to user GrpcJsonTranscoder to connect an Ocelot Api Gateway to a GRPC server hosted on .net-core but I am unable to do it with or without TLS.

With TLS activated on grpc-server I get:

```
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
         at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
         at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
```
without TLS enabled:
```
       ---> System.IO.IOException: The response ended prematurely.
         at System.Net.Http.HttpConnection.FillAsync()
         at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
```

How can I set GrpcJsonTranscoder to work without TLS? 

I know about this https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-3.0#call-insecure-grpc-services-with-net-core-client; is there a way to use it?

**Comment by thangchung** [comment]
@mihaimyh If you don't pass it down then it will use Insecure mode. See the code at https://github.com/thangchung/GrpcJsonTranscoder/blob/master/src/GrpcJsonTranscoder/DownStreamContextExtensions.cs#L62

We work on the new version at https://github.com/vietnam-devs/coolstore-microservices/tree/develop/src/building-blocks/GrpcJsonTranscoder, with more complex scenario can be found at https://github.com/vietnam-devs/coolstore-microservices/blob/develop/src/gateways/webapi-gateway/Program.cs. I will merge the latest version back to this repo soon. Will let you know after this process finish

**Comment by kollerdroid** [comment]
The same error for me. `(System.IO.IOException: The response ended prematurely.)`
When will be available the new working version?

**Comment by thangchung** [comment]
Try it again. I just deliver the update version on .NET Core 3.1. Feel free to re-open if it's still not working. Thank you

**Comment by kollerdroid** [comment]
The same error.
I checked the following:
```cs
var configuration = new OcelotPipelineConfiguration
{
    PreQueryStringBuilderMiddleware = async (context, next) =>
    {
        using var channel = GrpcChannel.ForAddress("http://localhost:7001");
        var client = new User.UserClient(channel);
        var result = await client.GetUserByEmailAsync(new GetUserRequest { Email = "em@i.l" });

        var jsonSerializer = new JsonSerializerSettings
        {
            ContractResolver = new CamelCasePropertyNamesContractResolver()
        };
        var response = new OkResponse<GrpcHttpContent>(new GrpcHttpContent(JsonConvert.SerializeObject(result, jsonSerializer)));

        var httpResponseMessage = new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = response.Data
        };

        context.HttpContext.Response.ContentType = "application/json";
        context.DownstreamResponse = new DownstreamResponse(httpResponseMessage);

        await next.Invoke(); //Causes System.IO.IOException: The response ended prematurely.
    }
};
```

It works when I remove the last line. I do not really know what happens in the pipeline after this...
